export const EMPLOYEE_TYPE = {
    CAMP_MANAGER:'CAMP_MANAGER',
    INSTRUCTION:'INSTRUCTION'
}

export const MODAL_TYPES = {
    EDIT_CAMP_MANAGER:'EDIT_CAMP_MANAGER',
    EDIT_INSTRUCTION:'EDIT_INSTRUCTION',
    EDIT_CHILDREN:'EDIT_CHILDREN'
}