export const EMPLOYEE_TYPE = {
    CAMP_MANAGER:'CAMP_MANAGER',
    INSTRUCTION:'INSTRUCTION'
}

export const MODAL_TYPES = {
    EDIT_CAMP_MANAGER:'EDIT_CAMP_MANAGER',
    EDIT_INSTRUCTION:'EDIT_INSTRUCTION',
    EDIT_CHILDREN:'EDIT_CHILDREN'
}

export const PERMISSIONS = {
    ADMIN:5,
    GENERAL_MANAGER:4,
    CAMP_MANAGER:3,
    TRANSPORT_MANAGER:2,
    INSTRUCTION:1,
}